### ISSUE TITLE
Improve XForm for Waterways

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-fieldwork#11]
Modify the XLSForm used for the Ruwa-Niger project used to collect data on waterways. The changes involve 2 things. The primary one is improving the efficiency of collecting map data. The secondary is to modify the XLSForm **name** column in the survey and choices sheets to be a closer match to approved OSM tags/values to make it easier to convert them from ODK to OSM.

**Comment by rsavoye** [comment]
This data model has been archived.
