### ISSUE TITLE
Add docstrings with parameters to all functions and auto-doc with mkdocs

### ISSUE THREAD

**Issue by neelimagoogly** [hotosm/osm-fieldwork#142]
I want to add support for [Sphinx](https://www.sphinx-doc.org/en/master/) to this project to easily auto-generate clean and well-organized documentation from Python code using Sphinx.
This was suggested to me by @robsavoye and after a perfect research now I am willing to work on this.
@robsavoye and @petya-kangalova please assign me this.

**Comment by spwoodcock** [comment]
My recommendation would be mkdocs instead of Sphinx https://www.mkdocs.org/

I have always found it much easier to implement and manage.

Plus it's nice to have readable markdown at the end, rather than reStructuredText.

The docstrings can be in any style: Google (my choice), numpy, reStructuredText.

This would only be a change to the auto documentation tooling.

**Comment by spwoodcock** [comment]
Example of a Google style docstring from a project I work on:

```python
    def get(
        self,
        key: str,
        response_content_type: str = None,
        decode: bool = False,
    ) -> (Any, dict):
        """Get an object from the bucket into a memory object.

        Defaults to utf-8 decode, unless specified.

        Args:
            key (str): The key, i.e. path within the bucket to get.
            response_content_type (str): Content type to enforce on the response.
                Defaults to None.
            decode (bool): Decodes using utf-8 if set. Useful for text based files.
                Defaults to None.

        Returns:
            tuple: (data, S3 Metadata dict).
        """
```

It would be great to update the function parameters at the same time to include type hinting (as this helps auto doc generation).

> Note If type hinting is added, the docstring parameters can also be generated with a tool.

**Comment by robsavoye** [comment]
I'd love to start fixing this code to use type hinting, since the FMTM backend also support this. It'll look more like C++ code this way. :-) This does look simpler than sphinx.

**Comment by robsavoye** [comment]
I did just fix all the code to use type hinting, although need to add the return types still.

**Comment by robsavoye** [comment]
We need to do a little research and decide between mkdocs or sphinx for API documentation.

**Comment by neelimagoogly** [comment]
> We need to do a little research and decide between mkdocs or sphinx for API documentation.

Ok
