### ISSUE TITLE
Refactor odk_merge.py from GDAL

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-fieldwork#148]
Right now odk_merge.py uses GDAL, which is often borderline unmaintainable by anyone not the primary author... Since now we have GeoJson formatted OSM data extracts for all  XLSForms, that or a local postgres should be the original data source for conflation.  The code should use psycopg2 and shapely instead of GDAL so it'll be more maintainable.

**Comment by robsavoye** [comment]
This is refactoring is initially done, now working on edge cases, improving the performance, and some debugging.

**Comment by spwoodcock** [comment]
I think we also need to refactor OGR out in basemapper.py https://github.com/hotosm/osm-fieldwork/blob/main/osm_fieldwork/basemapper.py to fully remote GDAL
