### ISSUE TITLE
Improve XForm for Market Places

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-fieldwork#15]
Modify the XLSForm used for the Ruwa-Niger project used to collect data on markets. These changes involve 2 things. The primary one is improving the efficiency of collecting map data. The secondary is to modify the XLSForm **name** column in the survey and choices sheets to be a closer match to approved OSM tags/values to make it easier to convert them from ODK to OSM.

**Comment by robsavoye** [comment]
In the new data models there is a category called **Businesses and Services**. This XLSForm will need to be heavily modified so it can support that data model.

**Comment by rsavoye** [comment]
This data model has been archived.
