### ISSUE TITLE
Allow custom SQL query upload for custom XLSForm

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/osm-fieldwork#196]
Related to FMTM issue that needs this: https://github.com/hotosm/fmtm/issues/509

Currently we only allow selection from predefined yaml files in the `data_extract` dir, meaning we can only create a data extract for a single feature type.

Allowing for a custom yaml file to be passed (uploaded by e.g. FMTM), would mean we can select multiple features when getting the data extract.

**Comment by robsavoye** [comment]
It looks like this is handled correctly when using the osm-rawdata module directly. It's only the library of XLSForms that have the canned data_models.

**Comment by spwoodcock** [comment]
So do we plan on using osm-rawdata directly for generating all data extracts, instead of `make_data_extract` in this package?
