### ISSUE TITLE
Set logger for command line calls

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/osm-fieldwork#207]
**Is your feature request related to a problem? Please describe.**

- We have getLogger in each module, and it works well when calling osm-fieldwork from other code.
- When using standalone modules we don't have a logger set to be hooked into.

**Describe the solution you'd like**

Loggers should be set like this:

https://github.com/hotosm/osm-fieldwork/blob/f66cd0cbbe1a5841f7ff33f53683423f3a1bc261/osm_fieldwork/OdkCentral.py#L1113

In every module `__main__` function.

OdkCentral.py is the only module with it currently.

**Comment by joemaren** [comment]
Do modules like ODKDump.py need to have loggers set?

**Comment by spwoodcock** [comment]
Yes I would say so - any file that is called via command line. 

There is already a logger set if the `verbose` param is set in some files.

I would say by default we should set a logger at the top of the `__main__` function with log level `INFO`. This will also print errors to terminal. 

Then if the `verbose` param is set, change the log level to `DEBUG` 👍

**Comment by spwoodcock** [comment]
Definitely! :tada

**Comment by spwoodcock** [comment]
Definitely! 😄

**Comment by donaldte** [comment]
Hello @spwoodcock  I would like to contribute to this issue can I ?

**Comment by spwoodcock** [comment]
Hi @donaldte , thanks for the interest!

I think that @owolabioromidayo may have already solved it though. 

We still need lots of improvements to test cases if you would like to work on those 🙏

**Comment by spwoodcock** [comment]
Fixed by #244
