### ISSUE TITLE
Amenity data model is broken

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/osm-fieldwork#228]
**Describe the bug**

- When the yaml is parsed and used by osm-rawdata to download a data extract, we get an error.
- Further debugging required.

**To Reproduce**

- Easily via FMTM frontend, selecting 'Amenity' form, then attempting to download a data extract.

**Expected behavior**

- The yaml is parsed into a format that works for raw-data-api filters.

**Comment by robsavoye** [comment]
Hum, it was working a few months ago, I'll have to check.

**Comment by spwoodcock** [comment]
I added this issue here as a reminder, as I haven't been able to debug thoroughly.

The issue is either in the data model itself, or in how it's parsed.

For parsing it could be either the input parsing to osm-rawdata QueryConfig, or the output parsing of the JSON for use with raw-data-api.

If it's that we can close the issue here and make one on osm-rawdata.

**Comment by robsavoye** [comment]
Most of HOT's field mapping is using the buildings XLSForm. I wrote Amenities for me when updating map data in small rural town focused on amenities instead of all the buildings.

**Comment by spwoodcock** [comment]
Completely agree.

@manjitapandey @Sujanadh we should probably just remove the categories / slim down the available categories in the read_xlsforms function.

**Comment by robsavoye** [comment]
I just tried this using local postgres for the extract, and it worked fine. I even tried it in Collect. While the building xlsform is great for mapping small areas, for large rural areas, it's too much data, most of which can be supplied by the basemap. This xlsform is focused on only updating amenities, typically businesses in small rural villages. The extract can cover a large area including multiple villages in the same extract, and a single xlsform. Often these villages have no amenities in OSM anyway, then they get added instead. If they do exist in OSM, then additional metadata can be collected.

**Comment by spwoodcock** [comment]
Thanks for verifying @robsavoye !

The issue is probably in the parsing via osm-rawdata then, not the data model itself.
