### ISSUE TITLE
Challenges with Docker on M-Series MacBook: Default Support Issue

### ISSUE THREAD

**Issue by Munanom** [hotosm/osm-fieldwork#232]
The current implementation of docker doesn’t not support running default on m series MacBook

The expected behavior when running is an error : no matching manifest for linux/arm64/v8 in the manifest list entries.

**Comment by spwoodcock** [comment]
Is the issue also with building the image yourself? Or just running?

Looks like the prebuilt images are not multiarch, but the base images to build yourself should be multiarch.

**Comment by spwoodcock** [comment]
For context there is a slack discussion about this. One possible fix:

[Img](https://hotosm.slack.com/files/U06N8M9858E/F06NL15NPJS/screenshot_2024-03-10_at_12.35.58.png)

Looks like our images are actually built multiarch, so this should not be an issue.

If you wish to run on ARM64 architecture (latest gen Macs), it's down to the user to configure their docker setup to work.

**Comment by spwoodcock** [comment]
For context there is a slack discussion about this. One possible fix:

[Img](https://hotosm.slack.com/files/U06N8M9858E/F06NL15NPJS/screenshot_2024-03-10_at_12.35.58.png)

Looks like our images are actually built multiarch, so this should not be an issue.

If you wish to run on ARM64 architecture (latest gen Macs), it's down to the user to configure their docker setup to work.

**Comment by Munanom** [comment]
Yes, I was the one who suggested this approach from slack after i was stuck, did some research and found a solution which fixed the error i was getting.

**Comment by spwoodcock** [comment]
An easier solution that would update your config globally is to add the following to your `.zshrc` file in your use directory:

```
export DOCKER_DEFAULT_PLATFORM=linux/arm64/v8
```
