### ISSUE TITLE
Add json2osm wrapper for use in downstream tools

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/osm-fieldwork#260]
**Describe the bug**

- json2osm.json2osm was commented out in v0.11.0
- This broke usage in FMTM.
- https://github.com/hotosm/osm-fieldwork/blob/1a94afff65c4653190d735f104c0644dcfb71e64/osm_fieldwork/json2osm.py#L269

**Expected behavior**

- The code should be un-commented and modified to work with the latest workflow here:

https://github.com/hotosm/osm-fieldwork/blob/1a94afff65c4653190d735f104c0644dcfb71e64/osm_fieldwork/json2osm.py#L326-L393

- Upstream tools can then use json2osm with a convenient wrapper, instead of having to write the same lines of code multiple times.

**Additional context**

- I added the breaking change to the release notes: https://github.com/hotosm/osm-fieldwork/releases/tag/0.11.0

**Comment by rsavoye** [comment]
I think this PR isn't needed now with the unified conversion PR that was merged this morning.
