### ISSUE TITLE
Move XLSForm mapping fields from XLS to code

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/osm-fieldwork#315]
**Is your feature request related to a problem? Please describe.**

- Follow on from discussion in https://github.com/hotosm/osm-fieldwork/pull/312

**Describe the solution you'd like**

- We should move the mandatory_fields form and digitisation form out of XLS format and into code.
- It's more verbose, but it's version controlled and more obvious what is being added.

**Comment by spwoodcock** [comment]
Following on from discussion in #312

We need a nice way to implement this without it being overly verbose and cumbersome. 

It's a bit of work, so we can consider this later after more pressing priorities

**Comment by manjitapandey** [comment]
But this way, if user don't want to add the injected fields on their projects. Adding the mandatory fields on code can be less flexible.

**Comment by spwoodcock** [comment]
I would argue it makes things more flexible, as we could probably have flags so the user can decide which fields they want. Say the need the geometry related questions, but don't want the photo verification for whatever reason `photo_question=False`.

The issue we have is that while simply merging in the XLS file keeps things simple, we have no idea what changes in the mandatory fields between osm-fieldwork releases. If it were in code, it's more obvious what fields changed over time 😄

**Comment by Sujanadh** [comment]
The first phase of building form on codebase is completed; we will further refine it moving forward.
