### ISSUE TITLE
Use OAM as imagery source

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-fieldwork#43]
If possible, use OpenArialMap as the imagery source for the basemapper.py program.

**Comment by robsavoye** [comment]
OAM reverses the order of the xyz values in the database from most other map tile servers use. I have this now working in a branch in order to produce basemaps for the Turkey earthquake, but it needs to be cleaned up and the result tested to make sure it doesn't break other imagery sources.

**Comment by spwoodcock** [comment]
This has already been complete via the --tms flag:

e.g.
```bash
pdm run osm_fieldwork/basemapper.py -b
 New_Kru_Town_MERGED.geojson -d $PWD -o New_Kru_Town_Basemap.mbtiles -z 12-24 --xy=True 
-t https://tiles.openaerialmap.org/5e6785161804990005e37072/0/5e6785161804990005e37073/{
z}/{x}/{y}
```

**Comment by spwoodcock** [comment]
The geojson content for those wishing to reproduce the mbtiles with the above command:

```json
{
"type": "FeatureCollection",
"name": "New_Kru_Town_MERGED2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 0, "country": "Liberia", "area": 1.7e-05, "perimeter": 0.016581 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -10.7938424154191, 6.36566446544188 ], [ -10.795144938864549, 6.369300019093447 ], [ -10.79320532649367, 6.370264783563053 ], [ -10.791896296184481, 6.370164711508116 ], [ -10.79146494532514, 6.369379587575136 ], [ -10.789732430818949, 6.366126169489173 ], [ -10.78956466274909, 6.365788466299136 ], [ -10.78991618820425, 6.365746651092064 ], [ -10.790463189266021, 6.365722411326678 ], [ -10.7938424154191, 6.36566446544188 ] ] ] } }
]
}
```

**Comment by Stephen-Tipa-Augustine** [comment]
I have solved the Outreachy contribution challenge and created a pull request in my forked repo, the link is below
https://github.com/Stephen-Tipa-Augustine/osm-fieldwork/pull/1

**Comment by Payne680** [comment]
@spwoodcock Please have a look at my PR, please am open for any feedback https://github.com/hotosm/osm-fieldwork/pull/235

**Comment by siva224513** [comment]
As per the Outreachy instructions, I'm posting my pull request link here. I've forked the repository, made the necessary changes, and created a pull request within my forked repository. Please  [find the link](https://github.com/hotosm/osm-fieldwork/pull/237) for review. Thank you!

**Comment by medinasheriff** [comment]
https://github.com/medinasheriff/osm-fieldwork/pull/1 @spwoodcock @petya-kangalova
