### ISSUE TITLE
Create CLI for CSVDump.py and odk_client.py

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/osm-fieldwork#56]
We are using these modules in FMTM, but running standalone would be easier with a CLI.
- odk_client is a CLI for odkcentral. It is more of a debugging tool, but its direct access into the DB lets you clean up mistakes that you can't do through the UI, like deleting projects.
- CSVDump.py is used to extract data for going to remote / offline mapping areas. Most OSM software requires an internet connection, so this is useful for those that regularly map offline.

I propose we add a CLI for these two modules using Click (https://pypi.org/project/click/), to install into a users bin after pip installing, allowing them to run something like:
`odkconvert client function --flag`
`odkconvert dump --flag`

**Comment by spwoodcock** [comment]
See #57 for more discussion on this.

**Comment by joemaren** [comment]
I'd like to look work on this @spwoodcock, although I might need a bit of hand-holding.

**Comment by joemaren** [comment]
@spwoodcock Do you mind assigning this task to me?

**Comment by spwoodcock** [comment]
Appreciate it @joemaren! I'm happy to help with whatever I can. Are you in the hotosm slack? https://slack.hotosm.org/

I just spent a while writing out how best to do this on my phone, but it refreshed and I lost it 😅 

In summary I was saying we should use click groups https://click.palletsprojects.com/en/8.1.x/commands/

We can have a single file called `cli.py` which imports functions from odk_client.py and ODKDump.py and wraps them with click decorators for all possible arguments.

So as in the docs above, we have a two @click.group functions, for both **client** and **dump**.

```python
from odkconvert.odk_client import func_to_call

@client.command(....
@client.option(...
def project(arg1):
    func_to_call(arg1)

Then we use @client.command to add subcommands and @client.option for flags.

The goals is to use the CLI like:
`odkclient client project --list`

**Comment by spwoodcock** [comment]
**Related question**

__Anon__:

from the goals you listed, you wanted the usage to be:
`odkconvert client project --list`
`odkconvert dump --csv --project 1`

I'm confused because from the docs it seems calling from the terminal should be something like:
`python cli.py client project --list`
`python cli.py dump --csv --project 1`

__My response__:
The exact syntax isn't set, I just made it up as an example without checking thoroughly.

But as for your specific question: using `python cli.py` syntax will run the `cli.py` module directly, which probably won't do anything (unless you have the `__main__` function set.

The aim is to use a package like `argparse` or more ideally `click`, which can use decorator syntax to make functions directly accessible from a terminal. The output will be a CLI executable/binary called `odkconvert`, which the user will install as part of the odkconvert pip package.
Then the user can run `odkconvert arg --flag` directly from their terminal.

**Comment by spwoodcock** [comment]
The argparse based CLI is working fine & adding `click`, while a nice addition, is not necessary.
Anyone can feel free to work on it, but it's not an essential addition.
Closing this issue.
