### ISSUE TITLE
Improve Osm-fieldwork wiki page

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-fieldwork#71]
ODKCOnvert could use a wiki page that has actual content.

**Comment by mohammadareeb95** [comment]
Can I work on submitting a PR towards this issue?

**Comment by mohammadareeb95** [comment]
## ODK Convert Project
ODKConvert is a project that aims to simplify the process of processing data collected using OpenDataKit into OpenStreetMap format. It consists of several utility programs that automate different parts of the data flow. These include creating satellite imagery basemaps and data extracts from OpenStreetMap so they can be used with ODK Collect. It is maintained by the [Humanitarian OpenStreetMap Team (HOT)](https://www.hotosm.org/) and designed to work with ODK Collect, an Android app for data collection, and ODK Central, a web-based platform for managing and visualizing data.

## odkconvert
This program converts the data collected from ODK Collect into the proper OpenStreetMap tagging schema. The conversion is controlled by a YAML file, which makes it easy to modify for other projects. The output is an OSM XML formatted file for JOSM. However, it is important to note that no converted data should ever be uploaded to OSM without first validating the conversion in JOSM. To do high-quality conversion from ODK to OSM, it's best to use the XLSForm library as templates, as everything is designed to work together.

ODKConvert includes the following utilities:

- make_data_extract.py: extracts OpenStreetMap data within a given boundary and category (e.g., buildings, amenities) using Overpass Turbo or a Postgres database.
- CSVDump.py: converts a CSV file downloaded from ODK Central to OSM XML format.
- odk2csv.py: converts an ODK XML instance file to the same CSV format used by ODK Central.
- ODKDump.py: extracts data from an ODK Collect instance XML file and converts it to OSM XML format.
- ODKForm.py: parses an ODK XML form file and extracts its fields and data types.
- ODKInstance.py: parses an ODK Collect instance XML file and extracts its fields and data values.
- ODKConvert also includes support modules, such as convert.py for processing YAML config files and osmfile.py for writing OSM XML output files.

## Installation
To install ODKConvert, you can either install it directly from the main branch using the command:
`pip install git+https://github.com/hotosm/odkconvert.git`

Or install the latest version from PyPI using: `pip install ODKConvert`

Note: installation requires GDAL >3.4 installed on your system.

## Usage
Each utility has its own command-line interface, with various options and arguments. You can find detailed instructions on how to use each utility by running it with the -h or --help option.

For example, to extract OSM data within a boundary polygon from Overpass Turbo, run:

`./make_data_extract.py --overpass --boundary mycounty.geojson`

This will create a GeoJSON file with the extracted data.

To convert a CSV file from ODK Central to OSM XML format, run:

`./CSVDump.py -i data.csv > output.osm`

This will create an OSM XML file with the converted data.

## Contributing
ODKConvert is an open-source project, and contributions are always welcome! If you want to contribute, please read the [contribution guidelines](https://chat.openai.com/CONTRIBUTING.md) and [code of conduct](https://chat.openai.com/CODE_OF_CONDUCT.md) first.

## License
ODKConvert is released under the [MIT License](https://chat.openai.com/LICENSE).

**Comment by mohammadareeb95** [comment]
This is a draft before I open a PR. @robsavoye please let me know what you think, thanks.

**Comment by robsavoye** [comment]
Actually it's under the AGPLv3 license. The output file isn't created from stdout, CSVDump uses the name of the input file, strips off the .csv, and generates 2 output files, one OSM XML of public data, and the other a GeoJson fie with all the data. Sometimes humanitarian mapping collects public data for OSM, and private data for the mapping project funders.

**Comment by mohammadareeb95** [comment]
Is this the right command: `./CSVDump.py -i data.csv` 
This will generate two output files - one OSM XML of public data, and the other a GeoJson fie with all the data.

**Comment by robsavoye** [comment]
correct.

**Comment by robsavoye** [comment]
If you push this as a PR, I'll approve it, and it'll populate the wiki.

**Comment by mohammadareeb95** [comment]
Okay I'll open a PR.

**Comment by mohammadareeb95** [comment]
![image](https://user-images.githubusercontent.com/77102111/225081019-3fd74001-fbcd-486d-93b1-a47f07133e7e.png)
Can someone help me with this?

**Comment by spwoodcock** [comment]
The Wiki is deployed: https://github.com/hotosm/odkconvert/wiki

As a prerequisite for this task.

**Comment by robsavoye** [comment]
Right now the wiki is just a list of other docs. It would be nice to have a landing page too.

**Comment by mohammadareeb95** [comment]
#84 renders Homepage.md as the wiki landing page

**Comment by robsavoye** [comment]
Right now the landing page for the osm-fieldwork wiki is very boring and somewhat out of date. The top page (Home.md) can be improved by adding a few pictures (I have a bunch), and being more of an introduction doc that explains the project better.
