### ISSUE TITLE
Improve XForm for Water Points

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-fieldwork#8]
Modify the XLSForm used for the Ruwa-Niger project used to collect data on water points. The changes involve 2 things. The primary one is improving the efficiency of collecting map data. The secondary is to modify the XLSForm **name** column in the survey and choices sheets to be a closer match to approved OSM tags/values to make it easier to convert them from ODK to OSM.

**Comment by robsavoye** [comment]
This the first XLSForm being modified to work with odkconvert and a more efficient mapper data input flow. Some of the **name** column values have been changed to be a match with what OSM uses. The conversion program supports the old values as well as the new ones, but the idea is to be more aligned with OSM for the times manual conversion is required.

**Comment by robsavoye** [comment]
Still to be done is apply the new data models to this XForm. This will require modifying the survey questions and answers. That's the next task for this XForm.

**Comment by rsavoye** [comment]
This data models has been archived.
