### ISSUE TITLE
 Osm-fieldwork has minimal documentation, it should be expanded, and include more examples.

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-fieldwork#80]
The subject says it all. Update all the examples to use the current command line arguments, and expand the descriptions.

**Comment by mohammadareeb95** [comment]
### `odkconvert convert`
This command is used to convert data from one format to another, specifically XLSForm and CSV files to OSM XML. It also allows you to specify a GPS trace file if you have one available.

### Options:

-x, --xlsform: Path to the XLSForm file to convert.
-c, --csv: Path to the CSV file to convert.
-g, --gps: Path to the GPX file containing GPS trace data.
-y, --yaml: Path to the output YAML file.
-o, --osm: Path to the output OSM XML file.

Examples:
- Convert an XLSForm file to OSM XML:

`odkconvert convert --xlsform /path/to/xlsform.xlsx --yaml /path/to/output.yaml --osm /path/to/output.osm
`
- Convert a CSV file to OSM XML:

`odkconvert convert --csv /path/to/csvfile.csv --yaml /path/to/output.yaml --osm /path/to/output.osm
`
- Convert a form with GPS traces to OSM XML:

`odkconvert convert --csv /path/to/csvfile.csv --gps /path/to/gpstraces.gpx --yaml /path/to/output.yaml --osm /path/to/output.osm
`
### `osm-extract`
This command is used to extract OpenStreetMap data within a specified boundary using either Overpass Turbo or a Postgres database.

Options:
-b, --boundary: The boundary for the area you want.
-c, --category: The category of OpenStreetMap data you want to extract.
-o, --output: Path to the output OSM XML file.
-t, --type: The type of OSM data to extract, either 'overpass' or 'postgres'. Defaults to 'overpass'.
-d, --database: The name of the Postgres database to use if using the 'postgres' type.

Examples:
- Extract buildings in a specified boundary using Overpass Turbo:
`osm-extract -b "bbox coordinates" -c building -o /path/to/output.osm
`
- Extract amenities in a specified boundary using Postgres:
`osm-extract -b "bbox coordinates" -c amenity -o /path/to/output.osm -t postgres -d dbname
`
### `CSVDump.py`
This command is used to convert a CSV file downloaded from ODK Central to OSM XML format.

### Options:

-i, --input: Path to the input CSV file.
-o, --output: Path to the output OSM XML file.

Example:
- Convert a CSV file downloaded from ODK Central to OSM XML format:

`python CSVDump.py -i /path/to/input.csv -o /path/to/output.osm
`
### `odk2csv.py`
This command is used to convert an ODK XML instance file to the same CSV format used by ODK Central.

### Options:

-i, --input: Path to the input ODK XML instance file.
-o, --output: Path to the output CSV file.

Example:
Convert an ODK XML instance file to CSV format:

`python odk2csv.py -i /path/to/input.xml -o /path/to/output.csv
`

###`odk-dump`

The odk-dump command extracts data from an ODK Collect instance XML file and converts it to OSM XML format. It takes the following arguments:
--input: specifies the path to the ODK Collect instance XML file.
--output: specifies the path to the output OSM XML file.
--osm-file: specifies the path to an existing OSM XML file that will be used as a template for the output OSM XML file. This argument is optional.

Example
`odk-dump /path/to/odk_instance.xml --osm /path/to/output.osm`

###`odk-form`

The odk-form command parses an ODK XML form file and extracts its fields and data types. It takes the following arguments:

--input: specifies the path to the ODK XML form file.
--output: specifies the path to the output YAML file.
--flatten: specifies whether to flatten the output YAML file. This argument is optional.

Example
`odk-form /path/to/odk_form.xml --yaml /path/to/output.yaml
`

###`odk-instance`
The odk-instance command parses an ODK Collect instance XML file and extracts its fields and data values. It takes the following arguments:

--input: specifies the path to the ODK Collect instance XML file.
--output: specifies the path to the output YAML file.
--form: specifies the path to the ODK XML form file that corresponds to the instance file. This argument is optional.
--flatten: specifies whether to flatten the output YAML file. This argument is optional.

Example
`odk-instance /path/to/odk_instance.xml --csv /path/to/output.csv
`

**Comment by mohammadareeb95** [comment]
Please let me know what improvements can be made @robsavoye

**Comment by robsavoye** [comment]
This issues is being replaced by new ones with a smaller scope.
